version: '3'
services:
  api-producao:
    build:
      context: .
      args:
        - BUILD_CONFIGURATION=Debug
      dockerfile: Dockerfile
    image: tech-challenge-soat1-grp13-producao:latest
    restart: on-failure    
    ports:
      - "5272:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=User ID=fiap;Password=SenhaLocalProducao;Host=postgres-db-producao;Port=5432;Database=techChallengeProducao;Pooling=true;
    depends_on:
      - postgres-db-producao

  postgres-db-producao:
    hostname: postgres-compose
    image: postgres
    environment:
      POSTGRES_PASSWORD: "SenhaLocalProducao"
      POSTGRES_USER: fiap
      POSTGRES_DB: techChallengeProducao
    ports:
      - "15438:5432"
    volumes:
      - tech-challenge-soat1-grp13-db-data-producao:/var/lib/postgresql/data

volumes:
  tech-challenge-soat1-grp13-db-data-producao: